
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOB2_EDQ","is_bot":false,"login":"jiaqiguan2003","name":""},"headRefName":"Jiaqi-ArticlesTable","number":44,"title":"Create database table for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/44"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"jonathan-READMeFix","number":43,"title":"Update Links and Create Task Table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/43"}]
