
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-MenuItem-PUT","number":67,"title":"Add updateUCSBDiningCommonsMenuItem endpoint to UCSBDiningCommonsMenuItemController","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/67"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-MenuItem-GET","number":66,"title":"Jonathan - Add getById endpoint to UCSBDiningCommonsMenuItemController","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/66"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-MenuItem-DELETE","number":65,"title":"Jonathan - Add deleteUCSBDiningCommonsMenuItem endpoint to UCSBDiningCommonsMenuItemController and tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/65"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-UCSBDiningCommonsMenuItemController","number":64,"title":"Jonathan - Create UCSBDiningCommonsMenuItemController, add GET (index) and POST","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/64"},{"author":{"id":"U_kgDOBqdaoA","is_bot":false,"login":"MeronDT","name":""},"headRefName":"Meron-RecRequestTableGET","number":63,"title":"Add GET (show) endpoint for single record in RecommendationRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/63"},{"author":{"id":"U_kgDOBqdaoA","is_bot":false,"login":"MeronDT","name":""},"headRefName":"Meron-RecRequestTableController","number":62,"title":"Add controller and controller test for Recommendation Request","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/62"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"jh-UCSBDiningCommonsMenuItem-create-db","number":61,"title":"Add database table for dining commons menu item","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/61"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganizationTable","number":51,"title":"Create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/51"}]
