
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganizationsDELETE","number":72,"title":"Add DELETE endpoint for a specific record in UCSBOrganizations table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/72"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganizationsGET","number":71,"title":"Add GET endpoint for single UCSBOrganizations ","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/71"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganizationController","number":70,"title":"CreateUCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/70"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganizationTable","number":51,"title":"Create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-2/pull/51"}]
